### ISSUE TITLE
Document new project integration in README (codeoffset)

### ISSUE THREAD

**Issue by robertmassaioli** [luciodj/BlueBoot#1]
I was looking through how this source code works because I have been scanning over various different bootloader designs to see what was out there and it took me a while to figure out that the reason that the Blinky.X source code is built to run at the right location is because you used the `--codeoffset=0x200` in your Makefiles. 

It would be great if you documented how you were supposed to set those flags for a new project. Can you configure that somewhere in the IDE or do you have to edit the Makefile for every file that you add?

That is what this issue is about: documenting, in the README, how you would go about writing a new project from scratch that was compatible with your Bootloader.

**Comment by robertmassaioli** [comment]
After a bit of searching I think that this is the way that you set the codeoffset for the Blinky.X project to be 0x200:

<img width="926" alt="screen shot 2017-01-09 at 9 26 16 am" src="https://cloud.githubusercontent.com/assets/149178/21754122/c677d198-d64d-11e6-97bd-e308dd9a1036.png">

That would be great in the README.

**Comment by luciodj** [comment]
Hi Robert, 
That is it, all “low side” boot loaders do imply an offset for the “application”.
This is well documented in the MPLAB XC8 compiler manual, but I agree with you, it would definitely be helpful to add it to the REAME for all beginners and the occasional browsers of the Blue boot project (and similar) …

BTW do you have experience with including pictures (links to) in the markup language accepted by GitHub?
I remember attempting to use the standard “markdown” links but failing to connect to the img files included in the project…

Thanks
	Lucio
